name: Lint (black and flake8)
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v7.0.1
      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.13.15"
      - name: Install pip package(s)
        # renovate: datasource=pypi depName=hatch
        run: pip install hatch==1.18.0
      - name: Run black formatter check
        run: hatch run dev:black --check --verbose src tests
      - name: Run flake8 linter
        run: hatch run dev:flake8